#!/usr/bin/env python3
"""
deadline_watcher.py — scheduled backfill helper for MISSING deadlines (issue #54).

For every active, visible listing that has no `deadline`, re-fetch the official
URL already stored on the listing and ask the model whether the page states a
hacker-facing APPLICATION or REGISTRATION deadline. Confident, evidence-backed
proposals are written to a markdown report (deadline_proposals.md); the workflow
opens an issue for a maintainer to review.

Safety rules (enforced below):
  - Only participant application/registration deadlines — never event dates,
    judge/mentor/sponsor deadlines, or prior-cycle dates.
  - Only high-confidence results with a quoted evidence snippet are proposed.
  - Never overwrites listings.json; never auto-applies. Review-only output.

Reuses the SSRF/TLS-hardened fetch from auto_extract.py.
"""

import json
import os
import re
import sys
from datetime import datetime

import util
from auto_extract import fetch_page_content

try:
    from openai import OpenAI
    HAS_OPENAI = True
except ImportError:
    HAS_OPENAI = False

REPORT_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "deadline_proposals.md"
)

PROMPT_TEMPLATE = """You are checking a hackathon's official page for a HACKER-FACING \
application or registration deadline (the date by which PARTICIPANTS must apply or register).

Hackathon: {title}
Host: {company}
URL: {url}

Page content:
{content}

Return ONLY a JSON object:
{{
  "found": true or false,
  "deadline": "YYYY-MM-DD" or null,
  "deadline_type": "application" | "registration" | "other" | null,
  "confidence": "high" | "medium" | "low",
  "evidence": "the exact short phrase copied from the page that states this deadline, or empty"
}}

Rules:
- Report ONLY a deadline for participants to apply or register.
- Do NOT report the event/hackathon date, judging dates, sponsor/mentor/volunteer \
deadlines, or any prior-year/prior-cycle date.
- If the page shows only an event date and no application/registration deadline, set found=false.
- Use confidence "high" ONLY when the page explicitly states an application or \
registration deadline with a clear, current calendar date.
- "evidence" MUST be a short quote copied verbatim from the page content."""


def _extract_deadline(client, listing, page):
    """Ask the model for a participant deadline. Returns a parsed dict or None."""
    prompt = PROMPT_TEMPLATE.format(
        title=listing.get("title", ""),
        company=listing.get("company_name", ""),
        url=page.get("url", ""),
        content=page.get("text", "")[:8000],
    )
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "Return only valid JSON."},
            {"role": "user", "content": prompt},
        ],
        temperature=0,
        max_tokens=400,
        timeout=60,
    )
    text = (resp.choices[0].message.content or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```json?\n?", "", text)
        text = re.sub(r"\n?```$", "", text)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def _accept(extracted, today=None):
    """Apply the safety rules. Returns (iso_deadline, evidence) or None.

    `today` (a date) is the reference point for the past-date guard; it defaults
    to the current date in PST. Passing it explicitly keeps the check
    deterministic in tests and consistent across a single run.
    """
    if not isinstance(extracted, dict) or not extracted.get("found"):
        return None
    if extracted.get("confidence") != "high":
        return None
    if extracted.get("deadline_type") not in ("application", "registration"):
        return None
    evidence = str(extracted.get("evidence") or "").strip()
    if not evidence:
        return None
    raw = str(extracted.get("deadline") or "").strip()
    try:
        parsed = util.parse_deadline_date(raw)
    except ValueError:
        return None
    # Reject past / prior-cycle dates. The prompt asks the model to avoid these,
    # but enforce it in code too: a page that says "Applications closed <past
    # date>" must never become a proposal.
    if today is None:
        today = datetime.now(util.PST).date()
    if parsed < today:
        return None
    return parsed.isoformat(), evidence


def _build_report(proposals):
    lines = [
        "## 🔎 Proposed deadlines for review",
        "",
        f"_Auto-generated by the deadline watcher. {len(proposals)} listing(s) "
        "missing a `deadline` had a high-confidence application/registration "
        "deadline on their official page._",
        "",
        "**Review each one before adding it to `.github/scripts/listings.json`.** "
        "Nothing here has been applied.",
        "",
    ]
    for p in proposals:
        # company/title come from listings.json and evidence is a verbatim quote
        # from an untrusted fetched page; sanitize (strip newlines/control chars,
        # truncate) so they can't break the markdown or smuggle @mentions/links
        # into the opened issue.
        company = util.sanitize_field(p["company"], max_len=120)
        title = util.sanitize_field(p["title"], max_len=160)
        evidence = util.sanitize_field(p["evidence"], max_len=280)
        url = util.sanitize_field(p["url"], max_len=500)
        lines += [
            f"### {company} — {title}",
            f"- **Proposed deadline:** `{p['deadline']}` ({p['type']})",
            f"- **Source:** {url}",
            f"- **Evidence:** > {evidence}",
            f"- **Listing id:** `{p['id']}`",
            "",
        ]
    return "\n".join(lines)


def main():
    listings = util.get_listings_from_json()
    candidates = [
        l
        for l in listings
        if l.get("is_visible", True)
        and l.get("active", True)
        and not l.get("deadline")
        and str(l.get("url", "")).startswith("http")
    ]
    print(f"{len(candidates)} active listing(s) missing a deadline.")

    if not candidates:
        util.set_output("has_content", "false")
        return

    if not HAS_OPENAI or not os.environ.get("OPENAI_API_KEY"):
        util.warn("OpenAI is not configured; skipping deadline extraction.")
        util.set_output("has_content", "false")
        return

    client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    today = datetime.now(util.PST).date()
    proposals = []
    for listing in candidates:
        url = util.clean_url(listing["url"])
        try:
            page = fetch_page_content(url)
            if "error" in page:
                util.warn(f"could not fetch {url}: {page['error']}")
                continue
            extracted = _extract_deadline(client, listing, page)
            accepted = _accept(extracted, today)
        except Exception as e:  # never let one listing abort the whole run
            util.warn(f"deadline check failed for {url}: {e}")
            continue
        if not accepted:
            continue
        iso, evidence = accepted
        proposals.append(
            {
                "id": listing.get("id", ""),
                "company": listing.get("company_name", ""),
                "title": listing.get("title", ""),
                "url": url,
                "deadline": iso,
                "type": extracted.get("deadline_type"),
                "evidence": evidence,
            }
        )
        print(f"Proposed {iso} for {listing.get('title')}")

    if not proposals:
        util.set_output("has_content", "false")
        print("No confident deadline proposals.")
        return

    with open(REPORT_FILE, "w") as f:
        f.write(_build_report(proposals))
    util.set_output("has_content", "true")
    util.set_output("count", str(len(proposals)))
    print(f"Wrote {len(proposals)} proposal(s) to {REPORT_FILE}")


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:
        util.fail(f"Unexpected error in deadline watcher: {e}")
